apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: as-show-workspace 
spec:
  steps:
    - name: show-workspace-contents
      image: quay.io/jduimovich0/as-build-tools
      script: |
        #!/usr/bin/env bash
        echo "Show workspace contents: $(pwd)" 
        du  -a   
  workspaces:
  - name: source
    description: source-dir 