apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: as-default-workspace 
  finalizers:	
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
