apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipelines-by-gitops
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: pipelines-by-gitops
    server: 'https://kubernetes.default.svc'
  source:
    path: pipelines
    repoURL: 'https://github.com/jduimovich/pipelines-as-gitops.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
